In [1]:
import pandas as pd
import numpy as np

In [2]:
headings = pd.read_csv('pluviograph_data.csv', header=None, nrows=1)
headings = headings.dropna(axis=1).iloc[0].values

In [3]:
headings

array(['Abermain', 'Abermain', 'Adamstown', 'Adamstown', 'Beresfield',
       'Beresfield', 'Broadmeadow', 'Broadmeadow', 'Cardiff Chlorinator',
       'Cardiff Chlorinator', 'Cessnock BC', 'Cessnock BC', 'Charlestown',
       'Charlestown', 'Chichester Dam', 'Chichester Dam', 'Dora Creek',
       'Dora Creek', 'Fingal Bay No. 1', 'Fingal Bay No. 1',
       'Lookout Reservoir (failed)', 'Lookout Reservoir (failed)',
       'Maitland No. 7', 'Maitland No. 7', 'Maryland', 'Maryland',
       'Mayfield', 'Mayfield', 'Medowie 3', 'Medowie 3', 'Merewether Hts',
       'Merewether Hts', 'Nelson Bay', 'Nelson Bay',
       'Raymond Terrace WWTW', 'Raymond Terrace WWTW', 'Shortland 1',
       'Shortland 1', 'Stockton 3', 'Stockton 3', 'Swansea 8',
       'Swansea 8', 'Tanilba Bay 1', 'Tanilba Bay 1', 'Teralba 1',
       'Teralba 1', 'Toronto WWTW (failed)', 'Toronto WWTW (failed)',
       'Upper Chichester', 'Upper Chichester', 'Wallsend', 'Wallsend',
       'Wangi Wangi', 'Wangi Wangi', 'Waratah', 'Waratah', 'Bolwarra 1A',
       'Bolwarra 1A', 'Branxton WWTW', 'Branxton WWTW'], dtype=object)

In [4]:
df = pd.read_csv('pluviograph_data.csv', header=0)
df = df.iloc[:, 0:-2]
df.columns = headings

In [5]:
def extract_location(df, location):
    """Extract columns corresponding to a location."""

    df_subset = df[location]
    new_header = df_subset.iloc[0]
    df_subset = df_subset[1:]
    df_subset.columns = new_header
    df_subset.set_index('Time', inplace=True)
    df_subset.columns = ['Cumulative Daily Rainfall',]
    df_subset['Cumulative Daily Rainfall'] = df_subset['Cumulative Daily Rainfall'].astype('float')

    return df_subset

In [6]:
df_location = extract_location(df, 'Adamstown')

In [7]:
df_location

                 Cumulative Daily Rainfall
Time
6/6/2007 11:58                         0.4
6/6/2007 12:01                         0.8
6/6/2007 12:07                         1.2
7/6/2007                               0.0
7/6/2007 2:46                          0.4
...                                    ...
10/6/2007 7:52                         6.2
10/6/2007 13:06                        6.4
11/6/2007                              0.0
11/6/2007 10:07                        0.2
12/6/2007 0:35                         0.0

[1142 rows x 1 columns]

In [8]:
rainfall = df_location['Cumulative Daily Rainfall'].values[1:] - df_location['Cumulative Daily Rainfall'].values[0:-1]
rainfall = np.clip(rainfall, a_min=0, a_max=None)
rainfall = np.insert(rainfall, 0, df_location['Cumulative Daily Rainfall'].values[0])
df_location['Rainfall'] = rainfall

In [15]:
df_location.sort_values(by=['Rainfall',], ascending=False)[0:10]

                Cumulative Daily Rainfall  Rainfall
Time
8/6/2007 17:23                      165.2      27.2
8/6/2007 16:24                       93.6       7.2
8/6/2007 16:35                      106.8       6.8
8/6/2007 16:05                       71.6       5.2
8/6/2007 16:56                      126.4       3.2
8/6/2007 16:15                       79.6       0.8
8/6/2007 21:14                      324.8       0.4
8/6/2007 22:08                      331.6       0.4
8/6/2007 19:28                      271.6       0.4
8/6/2007 22:26                      336.8       0.4

In [11]:
df_location[520:530]

                Cumulative Daily Rainfall  Rainfall
Time
8/6/2007 17:01                      136.4       0.4
8/6/2007 17:01                      136.8       0.4
8/6/2007 17:02                      137.2       0.4
8/6/2007 17:02                      137.6       0.4
8/6/2007 17:02                      138.0       0.4
8/6/2007 17:23                      165.2      27.2
8/6/2007 17:24                      165.6       0.4
8/6/2007 17:24                      166.0       0.4
8/6/2007 17:25                      166.4       0.4
8/6/2007 17:25                      166.8       0.4